### ISSUE TITLE
Master branch is not the same as the one published on NPM

### ISSUE THREAD

**Issue by vleong2332** [camelCaseDave/xrm-mock-generator#2]
I noticed that the `/dist/xrm-mock-generator.js` downloaded from NPM and the one built from the `master` branch is different.

NOTE: left is NPM, right is github/master

https://www.diffchecker.com/1mLlHbJQ

Any plan to update the NPM packages (this and xrm-mock) soon?

**Comment by camelCaseDave** [comment]
Thanks

Syncd and released v1.0.6 to NPM: https://www.npmjs.com/package/xrm-mock-generator
